version: "3.8"
services:
  battery2mqtt:
    image: sthopeless/battery2mqtt:latest
    environment:
      - MQTT_HOST=192.168.3.37
      - MQTT_PORT=1883
      - MQTT_USER=
      - MQTT_PASSWORD=
      - MQTT_TOPIC=battery2mqtt
      - MQTT_QOS=1
      - INTERVAL=60
      - MONITORED_CONDITIONS=status,capacity,energy_now,energy_full,energy_full_design,power_now,voltage_now
      - BATTERY_HEALTH=1
      - TIME_REMAINING=1
      - SHOW_UNITS=1
      - AC_ADAPTER=1
      - LOG_LEVEL=info
    volumes:
      - /sys/class/power_supply:/sys/class/power_supply:ro
    restart: unless-stopped
